# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftExample' do

  # Pods for SwiftExample
  pod 'Purchases', :path => '../../'
  pod 'mParticle-Apple-SDK', '~> 7.0'

end
